language: node_js
node_js:
  - "12"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
